\ProvidesClass{hw}
\LoadClass{article}

\RequirePackage{geometry}
\RequirePackage{amsmath}
\RequirePackage{amssymb}

\newcommand{\RR}{\mathbb{R}}
\newcommand{\NN}{\mathbb{N}}
\newcommand{\ZZ}{\mathbb{Z}}
\newcommand{\QQ}{\mathbb{Q}}

\newcommand{\IRing}[1]{\mathcal{O}_{#1}}

\newcommand{\mmax}[2]{\text{max}\{ #1 , #2 \}}

\newcommand{\makeheader}[1]{\noindent\textbf{\textit{Steven Rosendahl\\ Homework #1}}}

\geometry{margin=0.5in}
